### PR TITLE
Fix, test order-0 nodes

### PR DESCRIPTION
**Pull request by inducer**
@alexfikl Could you take a look?

### CODE REVIEW

**Review by alexfikl — APPROVED** [review]
Looks good to me! This works automagically for the tensor product parts, right?

**Comment by inducer** [comment]
> This works automagically for the tensor product parts, right?

*cough*

```
>>> mp.equispaced_nodes_for_space(mp.QN(3, 0), mp.Hypercube(3))
/home/andreas/src/modepy/modepy/nodes.py:478: RuntimeWarning: invalid value encountered in true_divide
  return (np.array(node_tuples_for_space(space), dtype=np.float64)
array([[nan],
       [nan],
       [nan]])
```

**Comment by alexfikl** [comment]
> > This works automagically for the tensor product parts, right?
> 
> _cough_

Close enough!

That's because it divides the node tuples by the order [there](https://github.com/inducer/modepy/blob/93bf8c1a6986fe86dc2ec200379380a4b97bca01/modepy/nodes.py#L468-L469) to get the equidistant nodes. Maybe it's better to just do a tensor product of the 1D equidistant nodes to reuse these changes?

**Comment by inducer** [comment]
There. All it takes some encouragement and a test. :P Thanks for nudging. Take another look?

**Review by alexfikl — APPROVED** [review]
:+1:

**Comment by inducer** [comment]
Thanks for taking a look!

**Pull request merged**
